[workspace]
resolver = "2"
members = ["ingest_spotify_data"]

[workspace.dependencies]
glob = "0.3.1" 
rusqlite = { version = "0.30.0", features = ["bundled"] }
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
