[package]
name = "ingest_spotify_data"
version = "0.1.0"
edition = "2021"

[dependencies]
glob = { workspace = true }
rusqlite = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
